# Form implementation generated from reading ui file 'AddDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddDialog(object):
    def setupUi(self, AddDialog):
        AddDialog.setObjectName("AddDialog")
        AddDialog.resize(392, 230)
        AddDialog.setMinimumSize(QtCore.QSize(392, 230))
        AddDialog.setMaximumSize(QtCore.QSize(392, 230))
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 180, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.KeyEdit = QtWidgets.QPlainTextEdit(parent=AddDialog)
        self.KeyEdit.setGeometry(QtCore.QRect(130, 110, 231, 61))
        self.KeyEdit.setObjectName("KeyEdit")
        self.label = QtWidgets.QLabel(parent=AddDialog)
        self.label.setGeometry(QtCore.QRect(50, 120, 61, 21))
        self.label.setObjectName("label")
        self.OtpNameEdit = QtWidgets.QLineEdit(parent=AddDialog)
        self.OtpNameEdit.setGeometry(QtCore.QRect(130, 40, 231, 21))
        self.OtpNameEdit.setText("")
        self.OtpNameEdit.setMaxLength(20)
        self.OtpNameEdit.setObjectName("OtpNameEdit")
        self.label_2 = QtWidgets.QLabel(parent=AddDialog)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 51, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(AddDialog)
        self.buttonBox.accepted.connect(AddDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AddDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddDialog)

    def retranslateUi(self, AddDialog):
        _translate = QtCore.QCoreApplication.translate
        AddDialog.setWindowTitle(_translate("AddDialog", "Add"))
        self.label.setText(_translate("AddDialog", "Key: "))
        self.OtpNameEdit.setPlaceholderText(_translate("AddDialog", "My First OTP"))
        self.label_2.setText(_translate("AddDialog", "Name: "))
