# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 554)
        MainWindow.setMinimumSize(QtCore.QSize(802, 554))
        MainWindow.setMaximumSize(QtCore.QSize(802, 554))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LogsEdit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.LogsEdit.setGeometry(QtCore.QRect(40, 310, 721, 181))
        self.LogsEdit.setReadOnly(True)
        self.LogsEdit.setObjectName("LogsEdit")
        self.OtpTable = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.OtpTable.setGeometry(QtCore.QRect(40, 40, 511, 192))
        self.OtpTable.setAutoFillBackground(False)
        self.OtpTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.OtpTable.setObjectName("OtpTable")
        self.OtpTable.setColumnCount(2)
        self.OtpTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.OtpTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.OtpTable.setHorizontalHeaderItem(1, item)
        self.FreshButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.FreshButton.setGeometry(QtCore.QRect(600, 190, 111, 21))
        self.FreshButton.setObjectName("FreshButton")
        self.DelButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.DelButton.setGeometry(QtCore.QRect(600, 130, 111, 21))
        self.DelButton.setObjectName("DelButton")
        self.AddButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(600, 70, 111, 23))
        self.AddButton.setObjectName("AddButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuConnect = QtWidgets.QMenu(parent=self.menubar)
        self.menuConnect.setObjectName("menuConnect")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtGui.QAction(parent=MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionRegistration_Tools = QtGui.QAction(parent=MainWindow)
        self.actionRegistration_Tools.setObjectName("actionRegistration_Tools")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuConnect.addAction(self.actionSettings)
        self.menuConnect.addAction(self.actionRegistration_Tools)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConnect.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyLightOTP"))
        item = self.OtpTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.OtpTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Now Key"))
        self.FreshButton.setText(_translate("MainWindow", "Fresh"))
        self.DelButton.setText(_translate("MainWindow", "Delete"))
        self.AddButton.setText(_translate("MainWindow", "Add"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuConnect.setTitle(_translate("MainWindow", "Connect"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionRegistration_Tools.setText(_translate("MainWindow", "Registration Tools"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
