# Form implementation generated from reading ui file 'RegistrationDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegistrationDialog(object):
    def setupUi(self, RegistrationDialog):
        RegistrationDialog.setObjectName("RegistrationDialog")
        RegistrationDialog.resize(400, 300)
        RegistrationDialog.setMinimumSize(QtCore.QSize(400, 300))
        RegistrationDialog.setMaximumSize(QtCore.QSize(400, 300))
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=RegistrationDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.UrlEdit = QtWidgets.QLineEdit(parent=RegistrationDialog)
        self.UrlEdit.setGeometry(QtCore.QRect(120, 50, 231, 21))
        self.UrlEdit.setObjectName("UrlEdit")
        self.label = QtWidgets.QLabel(parent=RegistrationDialog)
        self.label.setGeometry(QtCore.QRect(40, 50, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=RegistrationDialog)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 71, 21))
        self.label_2.setObjectName("label_2")
        self.UserIDEdit = QtWidgets.QLineEdit(parent=RegistrationDialog)
        self.UserIDEdit.setGeometry(QtCore.QRect(120, 100, 231, 21))
        self.UserIDEdit.setObjectName("UserIDEdit")
        self.PasswordEdit = QtWidgets.QLineEdit(parent=RegistrationDialog)
        self.PasswordEdit.setGeometry(QtCore.QRect(120, 150, 231, 21))
        self.PasswordEdit.setText("")
        self.PasswordEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.label_3 = QtWidgets.QLabel(parent=RegistrationDialog)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 71, 21))
        self.label_3.setObjectName("label_3")
        self.RegisterButton = QtWidgets.QPushButton(parent=RegistrationDialog)
        self.RegisterButton.setGeometry(QtCore.QRect(40, 190, 311, 23))
        self.RegisterButton.setObjectName("RegisterButton")

        self.retranslateUi(RegistrationDialog)
        self.buttonBox.accepted.connect(RegistrationDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(RegistrationDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RegistrationDialog)

    def retranslateUi(self, RegistrationDialog):
        _translate = QtCore.QCoreApplication.translate
        RegistrationDialog.setWindowTitle(_translate("RegistrationDialog", "Dialog"))
        self.UrlEdit.setPlaceholderText(_translate("RegistrationDialog", "example.com:1145"))
        self.label.setText(_translate("RegistrationDialog", "Server URL: "))
        self.label_2.setText(_translate("RegistrationDialog", "User ID: "))
        self.UserIDEdit.setPlaceholderText(_translate("RegistrationDialog", "Jack"))
        self.PasswordEdit.setPlaceholderText(_translate("RegistrationDialog", "123456"))
        self.label_3.setText(_translate("RegistrationDialog", "Password: "))
        self.RegisterButton.setText(_translate("RegistrationDialog", "Register!"))
