# Form implementation generated from reading ui file 'SettingDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingDialog(object):
    def setupUi(self, SettingDialog):
        SettingDialog.setObjectName("SettingDialog")
        SettingDialog.resize(400, 295)
        SettingDialog.setMinimumSize(QtCore.QSize(400, 295))
        SettingDialog.setMaximumSize(QtCore.QSize(400, 295))
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SettingDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.UrlEdit = QtWidgets.QLineEdit(parent=SettingDialog)
        self.UrlEdit.setGeometry(QtCore.QRect(120, 40, 241, 21))
        self.UrlEdit.setObjectName("UrlEdit")
        self.label = QtWidgets.QLabel(parent=SettingDialog)
        self.label.setGeometry(QtCore.QRect(30, 40, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=SettingDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 81, 21))
        self.label_2.setObjectName("label_2")
        self.UserIDEdit = QtWidgets.QLineEdit(parent=SettingDialog)
        self.UserIDEdit.setGeometry(QtCore.QRect(120, 80, 241, 21))
        self.UserIDEdit.setObjectName("UserIDEdit")
        self.label_3 = QtWidgets.QLabel(parent=SettingDialog)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 81, 21))
        self.label_3.setObjectName("label_3")
        self.PasswordEdit = QtWidgets.QLineEdit(parent=SettingDialog)
        self.PasswordEdit.setGeometry(QtCore.QRect(120, 120, 241, 21))
        self.PasswordEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.ProtocolBox = QtWidgets.QComboBox(parent=SettingDialog)
        self.ProtocolBox.setGeometry(QtCore.QRect(50, 170, 61, 21))
        self.ProtocolBox.setObjectName("ProtocolBox")
        self.ProtocolBox.addItem("")
        self.ProtocolBox.addItem("")
        self.SkipCertBox = QtWidgets.QCheckBox(parent=SettingDialog)
        self.SkipCertBox.setGeometry(QtCore.QRect(130, 170, 121, 21))
        self.SkipCertBox.setObjectName("SkipCertBox")

        self.retranslateUi(SettingDialog)
        self.buttonBox.accepted.connect(SettingDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SettingDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SettingDialog)

    def retranslateUi(self, SettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingDialog.setWindowTitle(_translate("SettingDialog", "Dialog"))
        self.UrlEdit.setPlaceholderText(_translate("SettingDialog", "example.com:1145"))
        self.label.setText(_translate("SettingDialog", "Server URL: "))
        self.label_2.setText(_translate("SettingDialog", "User ID: "))
        self.UserIDEdit.setPlaceholderText(_translate("SettingDialog", "Jack"))
        self.label_3.setText(_translate("SettingDialog", "Password: "))
        self.PasswordEdit.setPlaceholderText(_translate("SettingDialog", "123456"))
        self.ProtocolBox.setItemText(0, _translate("SettingDialog", "HTTP"))
        self.ProtocolBox.setItemText(1, _translate("SettingDialog", "HTTPS"))
        self.SkipCertBox.setText(_translate("SettingDialog", "Skip Https Cert"))
